version: "3"

services:
    web:
        build: '.'
        command: node server.js
        ports:
            - '8080:8080'
        environment: 
            - AUTH_KEY=helloThere!
            - DATABASE_URL=postgresql://root:root@local_pg_db:5432/safespace
        
    local_pg_db:
        image: postgres:12
        ports:
            - '5431:5432'
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: safespace
            POSTGRES_PASSWORD: root

        container_name: local_pg_container
